START TRANSACTION;

ALTER TABLE `projects`
  ADD COLUMN IF NOT EXISTS `start_date` DATE DEFAULT NULL AFTER `priority_id`,
  ADD COLUMN IF NOT EXISTS `end_date` DATE DEFAULT NULL AFTER `start_date`;

COMMIT;
